GOCMD=go
GOBUILD=$(GOCMD) build
GOCLEAN=$(GOCMD) clean

CMD_DIR=./cmd
BIN_DIR=./bin

WEB3SAFE_BINARY_NAME=web3safe
WEB3SAFE_CMD_DIR=$(CMD_DIR)/$(WEB3SAFE_BINARY_NAME)

DOTENVANALYZER_BINARY_NAME=dotenvanalyzer
DOTENVANALYZER_CMD_DIR=$(CMD_DIR)/$(DOTENVANALYZER_BINARY_NAME)

ENVANALYZER_BINARY_NAME=envanalyzer
ENVANALYZER_CMD_DIR=$(CMD_DIR)/$(ENVANALYZER_BINARY_NAME)

ifeq ($(OS),Windows_NT)
	WEB3SAFE_BINARY_NAME:= $(WEB3SAFE_BINARY_NAME).exe
	DOTENVANALYZER_BINARY_NAME:= $(DOTENVANALYZER_BINARY_NAME).exe
	ENVANALYZER_BINARY_NAME:= $(ENVANALYZER_BINARY_NAME).exe
endif

build: clean
	$(GOBUILD) -o $(BIN_DIR)/$(WEB3SAFE_BINARY_NAME) $(WEB3SAFE_CMD_DIR)/...
	$(GOBUILD) -o $(BIN_DIR)/$(DOTENVANALYZER_BINARY_NAME) $(DOTENVANALYZER_CMD_DIR)/...
	$(GOBUILD) -o $(BIN_DIR)/$(ENVANALYZER_BINARY_NAME) $(ENVANALYZER_CMD_DIR)/...

clean:
	$(GOCLEAN)
	rm -f $(WEB3SAFE_BINARY_NAME)
	rm -f $(DOTENVANALYZER_BINARY_NAME)
	rm -f $(ENVANALYZER_BINARY_NAME)

deps:
	$(GOCMD) mod tidy

test:
	$(GOCMD) test ./...

.PHONY: build clean deps test
